### PR TITLE
Doom: version 1.2 demo support and other improvements

### PR DESCRIPTION
**Pull request by JNechaevsky**

### CODE REVIEW

**Comment by Dasperal** [comment]
Is `-complevel 0` now also supported?

**Comment by JNechaevsky** [comment]
Yep, all demos from 1.2 and 1.25 versions are working fine.

**Comment by Dasperal** [comment]
I mean the command line parameter, I don't see any additions to its processing

**Comment by JNechaevsky** [comment]
Will do later, there is still some fun with 0.9 and 1.0 versions fonts loading because of Raven's code.
<details>

image

</details>

**Comment by JNechaevsky** [comment]
@fabiangreffrath, @rfomin, colleagues, by the chance, didn't you know why exactlly 1.2 / 1.25 was implemented as complevel? Is there some kind of story, or necessity, or was it most technically interesting version? Or something else? AFAIR, even first released non-GPL Doom source code was 1.10.

**Comment by rfomin** [comment]
> AFAIR, even first released non-GPL Doom source code was 1.10.

It's about DOS versions, https://doomwiki.org/wiki/Versions_of_Doom_and_Doom_II
I think Andrey's goal was to play every demo ever recorded without desync. By the way, the PrBoom+ implementation is probably not 100% compatible with the vanilla/Choco implementation.

**Comment by JNechaevsky** [comment]
Ah, maybe it is. Another possible thing is - Heretic is based Doom 1.2, so there was some special technical interest. 
I have checked, [Sleeping shotgun guy in MAP02](https://doomwiki.org/wiki/Sleeping_shotgun_guy_in_MAP02_(Doom_II)) bug is not happening for sure in 1.2 sight code. 🤓

**Comment by fabiangreffrath** [comment]
> @fabiangreffrath, @rfomin, colleagues, by the chance, didn't you know why exactlly 1.2 / 1.25 was implemented as complevel? Is there some kind of story, or necessity, or was it most technically interesting version? Or something else? AFAIR, even first released non-GPL Doom source code was 1.10.

Maybe @andrey-budko himself knows?

**Pull request merged**
