### PR TITLE
restore statdump, remove some I_Error calls in i_video

### PR DESCRIPTION
**Pull request by rfomin**
> remove some I_Error calls in i_video

This allows the game to run when the environment variable SDL_VIDEODRIVER=dummy is set. Therefore, SDL does not create an empty window with the -nodraw option, which speeds up automatic testing, and also allows to run on systems without proper graphics (WSL).

### CODE REVIEW

**Comment by JNechaevsky** [comment]
If it's or when it's done, please feel free to merge. it. There are no style restrictions or something else.

**Review by Dasperal — APPROVED** [review]

**Comment by JNechaevsky** [comment]
Quickly tried to compare ID <-> Woof generated stats, works fine, thank you! I still don't know how use `diff`, so Microsoft Excel could be used as well ([screenshot](https://user-images.githubusercontent.com/21193394/185847426-c867ee65-daf0-4924-9e4f-2338608580e4.png)). 😄

**Comment by rfomin** [comment]
> Quickly tried to compare ID <-> Woof generated stats, works fine, thank you! I still don't know how use `diff`, so Microsoft Excel could be used as well ([screenshot](https://user-images.githubusercontent.com/21193394/185847426-c867ee65-daf0-4924-9e4f-2338608580e4.png)). 😄

I like to use WinMerge, good program. https://winmerge.org/

**Comment by JNechaevsky** [comment]
Really good one, fairly clear how to use it. Thanks again!

**Comment by fabiangreffrath** [comment]
If you are in MSYS2 anyway, try meld: `mingw-w64-x86_64-meld3`

**Comment by JNechaevsky** [comment]
Oh, tied, also cool app. And there is a native Windows version at https://meldmerge.org, which have a proper drag-n-drop support.

**Comment by fabiangreffrath** [comment]
Meld does also have drag-n-drop support. But in the end, it's all `diff -u file1 file2`. 😁

**Comment by JNechaevsky** [comment]
My God, yes, turns out it is, now I know!... 😂

Regarding MELD - I've installed MSYS version and quickly tried to darg-n-drop file into GUI. For some reason, I've got warning in MSYS terminal and file wasn't chosen. Without any farther thoughs I decided to look up for native Windows version. According to personal feelings and nitpics, WinMerge rendering text slightly faster, probably because it was initially aimed for Windows and using some... Non cross-platform stuff for drawing. Or most probably I'm again counting milliseconds.

**Comment by rfomin** [comment]
> Or most probably I'm again counting milliseconds.

meld uses Python + GTK, it's very slow on Windows 😆 I used WinMerge for gigabytes logs, no problem.

**Comment by JNechaevsky** [comment]
A-ha, counting milliseconds wasn't that bad! I've come to it while benchmarking of vanilla level loading/reloading time and was totally unhappy by the fact that, for example, Industrial Zone was taking 10-12 ms. while it should take just 2-3 ms.  On low-end CPU difference was even bigger. Left some tests [here](https://github.com/JNechaevsky/inter-doom/pull/369#issue-1327639285), amazing personal experience, have to say.

Meanwhile, could I ask for another recommendation? ~Sooner~ or later I'll have to try to add BOOM map specifics support, but deffinitly not now. Not just because I'm not really familiar with BOOM mapping standard (boomedit.wad should be pretty good for checking), but mostly because of specifics themeselves are not just a couple of extra code lines with linedef specials and etc. It should be done carefully without hurry, otherwise any possible soft-lock on map will not make people and myself happy.

What is preffered code base for this? BOOM for DOS is probably easiest and shortest, but MBF for DOS or WinMBF have some fixes on top of it (with own bugs like three-keyed doors?). Woof is most modern and accurate, but it have MBF21 which is completelly different story and feels too complicated, probably it can be added far later. BOOM/MBF specific demos are out of question, complevels 2, 3 and 4 seems to be the most and only preffarable standards. So... Should I start from WinMBF?

**Comment by fabiangreffrath** [comment]
Let me say that I have attempted to "add Boom support" to Crispy Doom several times in the past, but always gave up for the exact same reasons you have already given. It's really not just a few new features, it's a complete engine rewrite with renamed enums, different indentation and comments, renamed functions and all that.

If I had to start again, I would indeed use WinMBF as the code base, because you would miss a lot of Killough's past-Boom optimizations if you focussed yourself on the pristine Boom source code. Plus, there is no way to quickly check changes with an actual executable if you are stuck to DOS (at least in my case that was a reason to concentrate on WinMBF, which actually compiles and runs fine on 32-bit Linux as well).

**Comment by rfomin** [comment]
Most PWADs since the late 2000s have never been tested in DOS Boom/MBF, so we ended up syncing playsim with PrBoom+ with Woof.

**Comment by fabiangreffrath** [comment]
Yes, right. You have to be careful as well with the subtle differences between PrBoom+'s complevel 9 and 11 and the actual Boom and MBF source codes! Good luck reading through PrBoom+'s spaghetti code for this. 😛

**Comment by JNechaevsky** [comment]
Oh, my... Clear, thanks! 🥲 On next life maybe, then. Or right after implementation of HD textures, wow-gfx effects, bloom, 3d models and other strictly necessary stuff for "playing Vanilla Doom in 2022"! _Read: never._

But still worth at least to try, I've made a long path and surprisingly, despite of being **very** emotional or morally exhausted while fails sometimes (not a big secret, hysteroid is my psychotype), no monitors or keyboards were destoyed for all this time and all planned things were done. For sure, that's because competent colleagues are always were nearby and no need to to point finger who it were exactlly. 😉

**Pull request merged**
