### PR TITLE
Libraries update

### PR DESCRIPTION
**Pull request by Dasperal**
See commit messages for details

### CODE REVIEW

**Comment by JNechaevsky** [comment]
A bomb. :heart: Fewer DLLs and ability to build with make - ninja is fine, but it's output isn't very user friendly.

**Comment by fabiangreffrath** [comment]
> ninja is fine, but it's output isn't very user friendly.

Try with the `-v` parameter.

**Comment by JNechaevsky** [comment]
Ouch my eyes! Thanks, I see, but was meaning slightly different thing: make is providing slightly neater and better formatted output.

**Comment by Dasperal** [comment]
It still has some bugs. Most I already fixed locally. The only thing left is different library names for "samplerate" in MSYS and in official builds. Looks like we need to provide dev distribution of "samplerate" for auto-builds.

**Pull request merged**
