### PR TITLE
Doom: colorize blood via HSV if custom PLAYPAL is loaded

### PR DESCRIPTION
**Pull request by JNechaevsky**
This should provide better compatibility with custom `PLAYPAL`s...

### CODE REVIEW

**Comment by JNechaevsky** [comment]
@fabiangreffrath, @rfomin, @mikeday0, 

Colleagues, this must be useful for Crispy. Here's how colored blood is looking on KDiKDiZD: [green](https://user-images.githubusercontent.com/21193394/202254344-47921ab5-f41a-4c4e-b02d-f6f6d6c5af02.png) and [blue](https://user-images.githubusercontent.com/21193394/202254475-b676849f-c442-461a-850f-4fd1160760c0.png). That's because of `CR_RED2X` is using color indexes from original `PLAYPAL`, while in KDiKDiZD palette colors are on different placements.

Easiest way was using just HSV's `CR_BLUE2` and `CR_GREEN` in R_ProjectSprite, but this way cool looking effect of two-colored curshed corpse will be lost on original palette, and I really want to keep it. The real problem is - we never know is modified palette is just using slightly or heavily different colors, so such strict check should provide reasonable farther compatibility with heavily modified palettes.

In Woof, however, blood looks almost okay except few incorrect pixels: [green](https://user-images.githubusercontent.com/21193394/202255481-fae65837-7d74-45b3-bcb0-975cc7399193.png) and [blue](https://user-images.githubusercontent.com/21193394/202255599-d1f7a8b2-3ad2-4290-95db-5f101c9ab5ef.png).

Any thoughts? :thinking:

**Comment by rfomin** [comment]
> In Woof, however, blood looks almost okay except few incorrect pixels: [green](https://user-images.githubusercontent.com/21193394/202255481-fae65837-7d74-45b3-bcb0-975cc7399193.png) and [blue](https://user-images.githubusercontent.com/21193394/202255599-d1f7a8b2-3ad2-4290-95db-5f101c9ab5ef.png).

I think that the situation with Woof is alright 😉 Why it's different from Crispy? I thought the implementation of colored blood feature is the same.

**Comment by fabiangreffrath** [comment]
The color translation tables in Crispy have been "optimized" back then.

**Comment by mikeday0** [comment]
I sadly lack a good understanding of the colored blood and color translation so I have no technical comment on this. However I will say maybe it would be nice to improve the messaging around this feature to indicate that a custom `PLAYPAL` will affect it.

**Comment by fabiangreffrath** [comment]
We could already mitigate the issue by simply returning back to the original Boom color translation tables (for `red2green` and `red2blue` only, that is) that everyone uses to check if color translations actually work as intended.

**Pull request merged**
