### PR TITLE
Fixing Mac build

### PR DESCRIPTION
**Pull request by atsb**
Currently this is an 'expected expression' error.  If it is a TODO, I'd suggest to comment it out :)

### CODE REVIEW

**Comment by Dasperal** [comment]
It is better to properly initialize the variable or at least initialize it with NULL.
The proper expression should be the same as for Linux but with MacOS's analog of `/usr/local/share`.

**Comment by atsb** [comment]
Exactly, though I didn't want to assume (I would leave that to the author).

**Comment by Dasperal** [comment]
I couldn't find information about where applications should install their components on macOS so I left the TODO there.

I'll try to search more once I start working on macOS support. Currently, it is the lowest priority for us because we don't use macOS even as a VM.

**Comment by atsb** [comment]
I noticed ;) on a Mac that path is there, it just isn't pretty.  Usually it is in ~/.config like Linux or special Mac paths like /Users/user/Library/Application Support/nameofapp

**Comment by Dasperal** [comment]
Ok, this should be
``` C
retVal = M_StringJoin(packageResourcesDir, resourceName, NULL);
```
Where `packageResourcesDir` is a result of [SDL_GetBasePath](https://wiki.libsdl.org/SDL_GetBasePath) call. The documentation says that "you should call it once and save the string" so `packageResourcesDir` should be initialized at startup in a different place.
Also need to test what this function returns on Windows and Linux in different scenarios.

So I think this should be implemented by me.

Also, improper fix(commenting out the line or initializing the variable with NULL) is useless since if the resource wasn't found RD just quits with an error.

**Comment by atsb** [comment]
I agree, since I guessed you were not yet ready for Mac support it was to get it building.  Not a proper fix at all, but was definitely better than breaking the build.  Thanks!  Just a tip, config file also cannot write to a .app bundle (execDir).  So that's something else to look at.

**Comment by Dasperal** [comment]
`RD_M_FindInternalResource` is for internal resources, they are read-only. Config dir is determent by [`GetDefaultConfigDir`](https://github.com/JNechaevsky/russian-doom/blob/master/src/m_config.c#L1201) implemented with [SDL_GetPrefPath](https://wiki.libsdl.org/SDL_GetPrefPath) on non Windows.

**Comment by JNechaevsky** [comment]
Hello @atsb, nice to see you here! 👋

Not much I can say further, as @Dasperal already stated, we are not using Mac in any ways.

**Comment by Dasperal** [comment]
Implemented `RD_M_FindInternalResource` for macOS in ceb12e0c60a100968c43158800c1256489e7a5a8

**Pull request closed without merging**
