### PR TITLE
Game mechanics: strict Vanilla mode

### PR DESCRIPTION
**Pull request by JNechaevsky**
There are tons of various, non-optional small game mechanics fixes. It is silly to make a tons of unclear switches, and in case of users want 100% vanilla mechanics, they is forced to use `-vanilla` parameter which is _"too conservative"_.

This feature should allow to get pure vanilla game mechanics while keeping all safe visual/audible/etc features.

### CODE REVIEW

**Comment by rfomin** [comment]
@JNechaevsky FYI, in DSDA-Doom and Woof "strict mode" is all about the DSDA (speedrunning community) rules. In essence, they disallow any changes to sprites or palettes, and PWAD options take precedence over user ones.

**Comment by JNechaevsky** [comment]
@rfomin, thanks for explanation! I think I've seen it, but was sure it's about gameplay features, not strict recourse usage. Here "strict_mode" is a variable name, in game menu it's a:
image
and
image

Really no idea how it can be renamed to something else unique + clear for understanding.

P.S. "Строгий ванильный режим" 🤡

**Comment by rfomin** [comment]
Oh, it's also gameplay restrictions, basically users can't change Boom/MBF options.
I don't know how to name it. To be honest, the speedrunning community is small and very hardcore, so I guess we don't confuse them (there are about 5 Woof users who record demos 😄)

**Comment by JNechaevsky** [comment]
Phew, good to know! Anyways, I should write a more-or-less proper explanation about it, not just a one changelog line. This release will be dedicated to six year anniversary, and honestly, getting back full "doom 1.9" demo compatibility (complevels 2, 3 and 4 if I'm not mistaking) and vanilla mechanics is something really worthy. 

Fixing vanilla bugs and spending hours and days for getting less milliseconds on loading something was a good experience, but having full backwards compatibility is even better.

**Comment by rfomin** [comment]
> getting back full "doom 1.9" demo compatibility (complevels 2, 3 and 4 if I'm not mistaking) and vanilla mechanics is something really worthy.

I think that to achieve full demo compatibility, you need to run automatic demo tests. There is a Compet-n demo archive, but since the ID is limit removing, it may be necessary to test the DSDA archive (there is an old backup from 2019 that I used: https://archive.org/details/dsda-2-final).
Not sure if it's worth it, I'm kind of obsessed with demo compatibility.
statcheck was used to test Choco/Crispy: https://github.com/chocolate-doom/statcheck

**Comment by JNechaevsky** [comment]
This is basically what I'm doing last days - watching various demos from [DSDA Archive](https://dsdarchive.com/). 😊

Using `-timedemo` first, and `-playdemo` later, to make sure everything is fine. Vanilla IWAD demos are working perfect, from short heavily TAS to longest ones like ~7 hours TNT's UV Fast. Long demos themselves are also perfect thing for crash checking - no longer need to stare to monitor for hours waiting that something went wrong, but rare silent crashes are fixed now, of course it was my oversight of using mixed `PU_STATIC` / `PU_CACHE`.

Latest checks shows that Spechit Overrun was also a critical thing and more interesting, centering Icon of Sin explosions wasn't safe at all: it is used on Eternal Doom MAP15 as a quirk, and may _potentially_ desync playable demos. Turns out, it was affecting game mechanics as well and _theoretically may_ make some maps impossible to finish. The chance is small but still... @fabiangreffrath, remember, we was having discussion about it few years ago? Here it is, now we know for sure - explosions are not just about MAP30 right before game ending. I believe, wrong explosions positioning may make kills stats slightly incorrect as well.

Thanks for DSDA archive, grabbing it! As about StatCheck, is there a quick example how to use it? I'm really not familiar with Python.

**Comment by rfomin** [comment]
> As about StatCheck, is there a quick example how to use it? I'm really not familiar with Python.

There is a wiki page: https://www.chocolate-doom.org/wiki/index.php/Statcheck

> Thanks for DSDA archive, grabbing it!

Without some kind of automation, it is useless (there is about 4.5 GB of demos/PWADs). I wrote a bunch of very ugly Python scripts to test the entire archive. Maybe @Dasperal will help.

**Comment by JNechaevsky** [comment]
Ah, download is finished and I see now: processing such structure with bare hands will be a nightmare, even with a lot of patience. 😨

Not a big loss, though, I still can check long-hours demos using `-timedemo`, demo timer and bar are extremely useful here.

Also, just tried to record a run of first three maps of Doom II on ID and run it in Crispy and Woof. It works! It's just a tiny maps, though, without any specific mapping quirks, but still a good sign.

**Comment by rfomin** [comment]
How test automation works:
run `inter-doom -nodraw -nosound -timedemo demo.lmp -statdump stat.txt`
Then `stat.txt` is compared with the `statdump` output of PrBoom+ or vanilla Doom.exe. You can write this automation in C or any other language. Python is just easier 😄

**Comment by fabiangreffrath** [comment]
> Not sure if it's worth it, I'm kind of obsessed with demo compatibility.

Me too, although I never seriously recorded any demo worth mentioning. The way I see it, everyone can mess around with the Doom source code. It's really not *that* hard. But once you lost demo compatibility, you have *broken* it.

> @fabiangreffrath, remember, we was having discussion about it few years ago? 

Yes, and I am glad I've been the one who raised the finger and predicted demo desyncs back then. 😁

**Comment by JNechaevsky** [comment]
@rfomin what a procedure! 😱 Thanks, I'll deffinitly try, at least for few demos.

@fabiangreffrath indeed, indeed. Another notable problems are experience, understanding and development route taken. Inititally, I was interested only in vanilla IWADs demo sync, but just a few days ago thought "but why not, if port actually can play demo, then it should be possible to fix desyncs". Frankly, was a bit painful to restore things which, well, wasn't "broken" _(in single player mode port becomes very crash-prone, especially on extreme scenes)_, but was removed as possible bugs, like overflowing, spechits and some other stuff. It cost me a bunch of nerves, but from another side, it brought new understading about some things which is always important. And of course, brought a couple of useful ideas which are avaiting your approval in Crispy Doom [#921](https://github.com/fabiangreffrath/crispy-doom/pull/921)! There are few more ideas, but I trying to keep my "flow" closed, otherwise an OVERflow may happen. 😆

Another fun thing is - I've never done serious and heavy benchmarking before, until you asked me about it in ... Was it drawsegs optimization in Woof, probably.

Sorry, I'm too talkative again. Just can't stop joying about good and right things are happening.

**Comment by rfomin** [comment]
> Sorry, I'm too talkative again. Just can't stop joying about good and right things are happening.

BTW we miss you on Discord 😄

**Comment by JNechaevsky** [comment]
I'm sorry... Have a strongest allergy now to any kind of messengers, social networks and other possible distractions. Despite of being _mostly_ a kind and positive person, I'm big introvert, and now preferring to do things quietly. Which is, by the way, according to latest port improvements, was a quite productive desition. 
☝️😁

**Comment by JNechaevsky** [comment]
Colleagues, I'm afraid I need advice. I've checked almost all DSDA demos for Doom 1, 2, Plutonia, TNT, Alien Vendetta, Hell Revealed, Memento Mori 1/2 and Requiem, from shortest to longest, recorded under different engines. Everything is fine, except just a two demos. Pff... Not really a thing I want to annoy with, but even full reverting of all P_, F_ and Wi_ code to vanilla doesn't helped.

So could you please advice, what else aside from that functions may affect demo sync? Probably G_ control handling? Or something in top level of "src" folder? 

I'm totally confused, because the rest of the demos, including tricks with spechits and intercepts overflow are fine.

**Comment by rfomin** [comment]
> Everything is fine, except just a two demos.

What demos? Note that there is two versions of Final Doom.

How I fix the desync: log all `P_Random()` calls on your port and the reference port (PrBoom+ or Choco), then compare the logs and get an approximate `gametic` when the desync occurs. After that, I usually instrument some P_ functions (`P_Move` etc.) and debug from there. Sometimes this process is long and convoluted.
See how logging is done in PrBoom+: https://github.com/coelckers/prboom-plus/blob/86bf4987d1d898856827afc1925deb351c342a71/prboom2/src/m_random.c#L91

**Comment by JNechaevsky** [comment]
These ones:

1. TNT (UV Speed, CNDoom v2.0.2): https://dsdarchive.com/files/demos/tnt/41233/evall-5236.zip, requires [tnt31.wad](https://www.wad-archive.com/wad/d292445192dd1ecb6e6e5350443755b9b2073255). Desync on MAP21 at ~36:15, when player bumps Mancubus.
2. [Requiem](https://dsdarchive.com/files/wads/doom2/3232/requiem.zip) (UV Speed, DRE / PRBoom v2.2.6.2cl2 / XDRE 2.14 | TAS): https://dsdarchive.com/files/demos/requiem/51186/30rqx2946.zip. Desyncs on MAP16 at ~14:22, when player... again, bumps Mancubus?

I've added demo warp from Crispy Doom, so there is no need to wait a lot to see what is happening. In Crispy and Woof everything is fine with same IWADs.

My first thought was about something is wrong with Mancubus, but probably it's just a coincidence. I've double-triple checked it's code and radius, they are totally fine. Neither it can be fixes related, all of them are under strict conditions (`singleplayer` and `strict_mode`), nor `FRACUNIT`, `MAPBLOCKUNITS` and etc., etc., etc., otherwise most of another demos will be obliviously desynced. Dead end. ☠️

**Comment by fabiangreffrath** [comment]
If there's a previous version of your port that plays these demos back fine, then `git bisect` can help. I have been in a similar situation with Crispy some years ago, where some two out of ~9000 demos would fail because of the Archvile fire coordinates fix and two more because of some fix I have applied to the IoS code.

**Comment by rfomin** [comment]
> ... at ~36:15, when player bumps Mancubus.

Desync could have occurred long before that. In my experience, visual cues are often useless and sometimes even misleading. I usually fix the desync with `-nodraw`.

I would start logging `P_Random()` calls. There is no universal recipe, it can be anything.

**Comment by JNechaevsky** [comment]
Understood, thanks both of you! Fortunately, same desync happens in released version on TNT and desyncs earlier on Requiem. I'm running demo checking as `-nodraw -timedemo -devparm`, it's really all needed to see which map is "jammed" in console output and saves a lot of time.

I will try different ways, from more harder reverting to P_Random checking, and this probably will be a deep dive. 🥽

Oh, and by the way, have a nice weekend!

**Comment by JNechaevsky** [comment]
Colleagues, I'm speechless. Problem with Requiem MAP16 was fixed pretty quickly (https://github.com/JNechaevsky/inter-doom/commit/ac6566371a75260b382701e31d1ea82d9325fc72) and after that demo playback starts to jamming on MAP21.

But. I've decided to re-check everything on both released versions Crispy Doom and Woof (both win32/64), and know what? Desyncs are absolutely same, on both Requiem and TNT demos! I even tried both TNT iwads, initial release and anthology, but it does not seems to be necessary since secret levels wasn't visited in both runs.

Again, here's the cursed demos:

* TNT's [evall-3845.zip](https://dsdarchive.com/files/demos/tnt/41223/evall-3845.zip) (Crispy Doom v5.1, 38:45)
* TNT's [evall-5236.zip](https://dsdarchive.com/files/demos/tnt/41233/evall-5236.zip) (CNDoom v2.0.2, 52:36)
* Requiem's [30rqx2946.zip](https://dsdarchive.com/files/demos/requiem/51186/30rqx2946.zip) (DRE / PRBoom v2.2.6.2cl2 / XDRE 2.14 / TAS, 29:46)

Turns out, I've done everything right, but... Is it something wrong with demos, or could it be OS specific, or starts aren't placed correctly? don't know what to think. Could you please check these demos on your side?

**Comment by rfomin** [comment]
Read demos .txt, you need `req21_competn.wad` for Requiem. There is fixes for TNT.WAD too. Downloads are on DSDA.

**Comment by rfomin** [comment]
Not sure about these TNT demos, Crispy 5.1 from 2018 may have had a desync that was fixed later, never tested CNDoom.

If PrBoom+ and Choco get out of sync, then I consider the demos to be broken.

**Comment by JNechaevsky** [comment]
Thanks, Roman. Guess I've got overheat after couple of last days. But now all job is done and complevels 2, 3 and 4 can be declared as supported (er, "implemented back"), along with full vanilla mechanics available in one simple menu item.

Better I take some rest now, and of course self-note:
image

**Comment by fabiangreffrath** [comment]
> Not sure about these TNT demos, Crispy 5.1 from 2018 may have had a desync that was fixed later, never tested CNDoom.

Sad but possible. Do you know which map the defunct occurs on? Does it happen to include an Archvile or an IOS?

> If PrBoom+ and Choco get out of sync, then I consider the demos to be broken.

Exact!

**Comment by JNechaevsky** [comment]
> Sad but possible. Do you know which map the defunct occurs on? Does it happen to include an Archvile or an IOS?

It is MAP21, again. Most probably it was caused by [staircase building fix](https://github.com/chocolate-doom/chocolate-doom/commit/355e1d8d1d9935dbf902d81d53e410a5308045e4) (dated 2019-02-18 in Choco), while 30ev3858 was recorded on 2019-02-09 and 30ev5236 was recorded on 2014-02-18, i.e. both demos were recorded before fix.

Here it is: [screenshot](https://user-images.githubusercontent.com/21193394/185750247-a689252f-92bd-43b2-9be8-4e757d0d2bf6.png). That fix was the last missing thing for demo syncs.

**Comment by fabiangreffrath** [comment]
OMG, that was my fault back then. One of the darkest spots in my commit history. 😭

**Comment by rfomin** [comment]
@JNechaevsky I ran some automated tests and found desyncs in the `d64d2.wad` demos (`-nomonsters` don't seem to work in Inter Doom)
<details>
  <summary>diff</summary>

```diff
*** C:/develop/demo-test/log-inter-doom.txt     Sun Aug 21 23:36:30 2022
--- C:/develop/demo-test/log-woof.txt   Sun Aug 21 23:36:54 2022
***************
*** 107,112 ****
--- 107,123 ----
        Secrets: 6 / 6 (100%)
  
  dsda/d64d2\d6403o051.lmp
+ ===========================================
+ E1M3 / MAP03
+ ===========================================
+ 
+ Time: 0:51 (par: 2:00)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 6 / 36 (16%)
+       Secrets: 0 / 6 (0%)
+ 
  dsda/d64d2\d6404-221.lmp
  ===========================================
  MAP04
***************
*** 120,125 ****
--- 131,147 ----
        Secrets: 5 / 5 (100%)
  
  dsda/d64d2\d6404o042.lmp
+ ===========================================
+ MAP04
+ ===========================================
+ 
+ Time: 0:42 (par: 2:00)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 0 / 16 (0%)
+       Secrets: 0 / 5 (0%)
+ 
  dsda/d64d2\d6404p050.lmp
  ===========================================
  MAP04
***************
*** 157,162 ****
--- 179,195 ----
        Secrets: 2 / 2 (100%)
  
  dsda/d64d2\d6405o131.lmp
+ ===========================================
+ MAP05
+ ===========================================
+ 
+ Time: 1:31 (par: 1:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 3 / 27 (11%)
+       Secrets: 0 / 2 (0%)
+ 
  dsda/d64d2\d6406-306.lmp
  ===========================================
  MAP06
***************
*** 194,199 ****
--- 227,243 ----
        Secrets: 0
  
  dsda/d64d2\d6408o117.lmp
+ ===========================================
+ MAP08
+ ===========================================
+ 
+ Time: 1:17 (par: 2:00)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 1 / 84 (1%)
+       Secrets: 0 / 3 (0%)
+ 
  dsda/d64d2\d6409-349.lmp
  ===========================================
  MAP09
***************
*** 207,213 ****
--- 251,279 ----
        Secrets: 3 / 3 (100%)
  
  dsda/d64d2\d6409o132.lmp
+ ===========================================
+ MAP09
+ ===========================================
+ 
+ Time: 1:32 (par: 4:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 0 / 36 (0%)
+       Secrets: 0 / 3 (0%)
+ 
  dsda/d64d2\d6410o108.lmp
+ ===========================================
+ MAP10
+ ===========================================
+ 
+ Time: 1:08 (par: 1:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 2 / 19 (10%)
+       Secrets: 0 / 3 (0%)
+ 
  dsda/d64d2\d6411-043.lmp
  ===========================================
  MAP11
***************
*** 245,250 ****
--- 311,327 ----
        Secrets: 5 / 5 (100%)
  
  dsda/d64d2\d6412o047.lmp
+ ===========================================
+ MAP12
+ ===========================================
+ 
+ Time: 0:47 (par: 2:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 2 / 24 (8%)
+       Secrets: 0 / 5 (0%)
+ 
  dsda/d64d2\d6413-419.lmp
  ===========================================
  MAP13
***************
*** 258,263 ****
--- 335,351 ----
        Secrets: 3 / 3 (100%)
  
  dsda/d64d2\d6413o121.lmp
+ ===========================================
+ MAP13
+ ===========================================
+ 
+ Time: 1:21 (par: 2:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 8 / 30 (26%)
+       Secrets: 0 / 3 (0%)
+ 
  dsda/d64d2\d6414o046.lmp
  ===========================================
  MAP14
***************
*** 307,312 ****
--- 395,411 ----
        Secrets: 3 / 3 (100%)
  
  dsda/d64d2\d6416o132.lmp
+ ===========================================
+ MAP16
+ ===========================================
+ 
+ Time: 1:32 (par: 2:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 0 / 22 (0%)
+       Secrets: 0 / 3 (0%)
+ 
  dsda/d64d2\d6417o054.lmp
  ===========================================
  MAP17
***************
*** 320,326 ****
--- 419,447 ----
        Secrets: 0 / 1 (0%)
  
  dsda/d64d2\d6418o054.lmp
+ ===========================================
+ MAP18
+ ===========================================
+ 
+ Time: 0:54 (par: 2:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 1 / 3 (33%)
+       Secrets: 0 / 2 (0%)
+ 
  dsda/d64d2\d6419o124.lmp
+ ===========================================
+ MAP19
+ ===========================================
+ 
+ Time: 1:24 (par: 3:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 13 / 54 (24%)
+       Secrets: 0 / 3 (0%)
+ 
  dsda/d64d2\d6420-152.lmp
  ===========================================
  MAP20
***************
*** 334,339 ****
--- 455,471 ----
        Secrets: 1 / 1 (100%)
  
  dsda/d64d2\d6422o224.lmp
+ ===========================================
+ MAP22
+ ===========================================
+ 
+ Time: 2:24 (par: 2:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 3 / 19 (15%)
+       Secrets: 0 / 7 (0%)
+ 
  dsda/d64d2\d6423-032.lmp
  ===========================================
  MAP23
***************
*** 378,384 ****
  Time: 0:27 (par: 3:00)
  
  Player 1 (Green):
!       Kills: 0 / 12 (0%)
        Items: 1 / 2 (50%)
        Secrets: 1 / 2 (50%)
  
--- 510,516 ----
  Time: 0:27 (par: 3:00)
  
  Player 1 (Green):
!       Kills: 0
        Items: 1 / 2 (50%)
        Secrets: 1 / 2 (50%)
  
***************
*** 419,424 ****
--- 551,567 ----
        Secrets: 3 / 3 (100%)
  
  dsda/d64d2\d6425o121.lmp
+ ===========================================
+ MAP25
+ ===========================================
+ 
+ Time: 1:21 (par: 2:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 8 / 37 (21%)
+       Secrets: 0 / 3 (0%)
+ 
  dsda/d64d2\d6426-142.lmp
  ===========================================
  MAP26
***************
*** 444,449 ****
--- 587,603 ----
        Secrets: 0
  
  dsda/d64d2\d6427o128.lmp
+ ===========================================
+ MAP27
+ ===========================================
+ 
+ Time: 1:28 (par: 5:30)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 33 / 64 (51%)
+       Secrets: 0 / 4 (0%)
+ 
  dsda/d64d2\d6428-759.lmp
  ===========================================
  MAP28
***************
*** 457,462 ****
--- 611,627 ----
        Secrets: 4 / 4 (100%)
  
  dsda/d64d2\d6428o317.lmp
+ ===========================================
+ MAP28
+ ===========================================
+ 
+ Time: 3:17 (par: 7:00)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 16 / 47 (34%)
+       Secrets: 0 / 4 (0%)
+ 
  dsda/d64d2\d6430-135.lmp
  ===========================================
  MAP30
***************
*** 513,523 ****
  Time: 0:01 (par: 2:00)
  
  Player 1 (Green):
!       Kills: 0 / 8 (0%)
        Items: 0 / 91 (0%)
        Secrets: 0 / 5 (0%)
  
  dsda/d64d2\d6431o040.lmp
  dsda/d64d2\d6431p001.lmp
  ===========================================
  MAP31
--- 678,699 ----
  Time: 0:01 (par: 2:00)
  
  Player 1 (Green):
!       Kills: 0
        Items: 0 / 91 (0%)
        Secrets: 0 / 5 (0%)
  
  dsda/d64d2\d6431o040.lmp
+ ===========================================
+ MAP31
+ ===========================================
+ 
+ Time: 0:40 (par: 2:00)
+ 
+ Player 1 (Green):
+       Kills: 0
+       Items: 23 / 91 (25%)
+       Secrets: 1 / 5 (20%)
+ 
  dsda/d64d2\d6431p001.lmp
  ===========================================
  MAP31
```
</details>

Demos archive with WADs: [d64d2.zip](https://github.com/JNechaevsky/inter-doom/files/9389601/d64d2.zip)

Are you interested in mass demo testing? (~40,000 demos) I can run it for you, but I need a few small changes to Inter Doom (eg -statdump) I can make PR.

**Comment by JNechaevsky** [comment]
😨 Please never pronounce "desync" word again, I can have a heart attack!

Thanks! If I'm reading this log correct, it says: ~"d6423-032.lmp and d6430-135.lmp have incorrect kill counters on tally screen", right? If so, it's probably caused by [this](https://github.com/JNechaevsky/inter-doom/blob/master/src/doom/p_mobj.c#L694-L699) correction, which is somehow counted wrong, since it's `singleplayer` only.~ 

**Edit:** Oh, wrong, there are monsters on map while they shouldn't appear. Commander Keen is breaking sync [here](https://github.com/JNechaevsky/inter-doom/blob/master/src/doom/p_mobj.c#L1226-L1227).

> Are you interested in mass demo testing? (~40,000 demos) I can run it for you, but I need a few small changes to Inter Doom (eg -statdump) I can make PR.

Only and exactly you have time and will for this. I can't let myself to annoy anyone with "I've break something, please fix all the thing for me", that's why I'm always asking for advice or recommendation. I've sent you collaboration invite, please feel free to proceed.

**Comment by rfomin** [comment]
> I've sent you collaboration invite, please feel free to proceed.

Thank you for the invitation, although I do not promise much activity. I just love demo testing for some reason and use any excuse to run these scripts 😄

**Pull request merged**
