### PR TITLE
Port M_NormalizeSlashes from Chocolate Doom

### PR DESCRIPTION
**Pull request by hfc2x**
Related to #215

### CODE REVIEW

**Comment by JNechaevsky** [comment]
Nope, not working. :( By moving `M_NormalizeSlashes` from Strife to `d_iwad.c` and then using it like:

```
static GameMission_t IdentifyIWADByName(char *name, int mask)
{
    size_t i;
    GameMission_t mission;
    char *p;

    p = strrchr(name, DIR_SEPARATOR);
+++ M_NormalizeSlashes(name);
+++ printf ("- IWAD path: %s \n", name);

    if (p != NULL)
    {
        name = p + 1;
    }
```

And using command `russian-doom.exe -iwad E:/TNT.wad`, I'm getting correct path:
```
- IWAD path: E:\TNT.wad
W_Init: Init WADfiles.
 loading: E:\TNT.wad
```

But still, game is considered as HoE, not TNT.

**Comment by JNechaevsky** [comment]
Fixed, now both `-iwad E:/TNT.wad` and `-file E:/test.wad` working! 
Starting game via ZDL working fine as well. :relieved:

@hfc2x thanks!

**Comment by hfc2x** [comment]
So Final Doom IWADs are working properly now?

**Comment by JNechaevsky** [comment]
Yep, everything is fine now. The only thing I haven't checked yet - how it will work on Linux.

**Comment by JNechaevsky** [comment]
On Linux seems to be fine by invoking:

```
./russian-doom -iwad /home/julian/TNT.wad 
```

And not starting by using this command line, giving an error message `IWAD file ' file 'homejulianTNT.wad' not found!
!`
```
./russian-doom -iwad \home\julian\TNT.wad 
```
...which is odd, because it should be catched by condition this condition: https://github.com/JNechaevsky/russian-doom/commit/d87312818439600240dd16f6e4b948364a0bdf43#diff-7283c8a6b6315a300c4f3414185ed3ccb8fe140625a0ea0168ffd33367d70732R699

Not a big problem though, AFAIR, paths on Unix should always use slashes (`/`), it's on system level.

**Comment by fabiangreffrath** [comment]
Probably because backslash is already interpreted by the shell. Try to put the whole path into single quotes.

**Pull request closed without merging**
